### ISSUE TITLE
Introduce latest branch

### ISSUE THREAD

**Issue by TheLavaBlock** [pezcode/conan-liblava#1]
Hey 🤠 

I would like to transfer the latest version from https://github.com/liblava/conan-liblava to yours. It would be good if we introduce a main branch 'latest', which we can keep up to date (after a release for example) and branch off 'stable' branches for the versions. 

Then I can remove the fork in the organization.

Or if you like, we can manage it in @liblava

Cheers

**Comment by pezcode** [comment]
I'm not much of a conan user myself, so keeping it here is a little useless since I won't be updating or testing this much. So I think the best idea would be to keep it in @liblava. Makes it easier to discover, and you can add new releases without relying on someone else.

If the reason you're asking is because you don't want to deal with the maintenance either 🤡, I'd still suggest keeping it in @liblava and letting people send PRs if they want latest versions.

So if you're alright with that, I'd just delete this repo to prevent confusion.

**Comment by TheLavaBlock** [comment]
This sounds like a plan. 👍 Yeah, I don't use it myself either...

Maintenance is not that much of a task at the moment, as there are no big changes in **liblava**.

**Comment by TheLavaBlock** [comment]
Btw, I give you access to that repo.
